# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 76226d885d3a814d403d483d48d03c0403b25babd1a3b79c0591f1e0688b19eecc22bf685f973063a356e721f02751de9f2132502ea5889c1a22497c2b11aefd

test:
  secret_key_base: 9911fd4f9d39a15f7f24f4adb2ab9f5121865bfc7bd9eb0f91115031be10a3872bb363676c354682dfcc03f2324d0975d50ee78665d9c73cdb71503d07ccfb02

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
